SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `AddOn` (
  `AddOnId` INT NOT NULL AUTO_INCREMENT,
  `AddOnCategoryId` INT NULL,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `CategoryId` INT NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Duration` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `ProductDurationId` INT NULL,
  `ProductExtraId` INT NULL,
  `ProductId` INT NULL,
  `ProductTranslationId` INT NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`AddOnId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AddOnCategory` (
  `AddOnCategoryId` INT NOT NULL AUTO_INCREMENT,
  `AddOnId` INT NULL,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `CategoryId` INT NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Duration` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `ProductDurationId` INT NULL,
  `ProductExtraId` INT NULL,
  `ProductId` INT NULL,
  `ProductTranslationId` INT NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`AddOnCategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Admin` (
  `AdminId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `BusinessTypeId` INT NULL,
  `City` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `ContactNumber` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Distance` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EncryptedOrganisationLocationId` INT NULL,
  `Floor` VARCHAR(512) NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrgLoc` VARCHAR(512) NULL,
  `OrganisationId` INT NULL,
  `OrganisationLocationId` INT NULL,
  `Password` VARCHAR(255) NULL,
  `ProfileImagePath` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `Street` VARCHAR(512) NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `Zip` VARCHAR(512) NULL,
  `ascending` VARCHAR(512) NULL,
  PRIMARY KEY (`AdminId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AdminNotificationContact` (
  `AdminNotificationContactId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `Value` DECIMAL(14,4) NULL,
  PRIMARY KEY (`AdminNotificationContactId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AppVersion` (
  `AppVersionId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Platform` DECIMAL(14,4) NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`AppVersionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Bank` (
  `BankId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `BankKey` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`BankId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Booking` (
  `BookingId` INT NOT NULL AUTO_INCREMENT,
  `AGPromoCodeId` INT NULL,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `B2B` VARCHAR(512) NULL,
  `BookedBy` VARCHAR(512) NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingProductAddOnId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `CSNotes` TEXT,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `CheckOutTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `ColorCode` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurrentBookingId` INT NULL,
  `CustomerId` INT NULL,
  `DD` VARCHAR(512) NULL,
  `DOB` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraAddOn` VARCHAR(512) NULL,
  `ExtraNotified` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `FcmToken` TEXT,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HH` VARCHAR(512) NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `MMM` VARCHAR(512) NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentIntent` VARCHAR(512) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `REGEXP` VARCHAR(512) NULL,
  `RatingId` INT NULL,
  `ReachOutTime` DATETIME NULL,
  `RealFinishTime` DATETIME NULL,
  `RealStartTime` DATETIME NULL,
  `RequestStatus` VARCHAR(512) NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffId` INT NULL,
  `StaffNotes` TEXT,
  `StaffVacConflict` VARCHAR(512) NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `SystemPhase` VARCHAR(512) NULL,
  `Therapist` VARCHAR(512) NULL,
  `TherapistNotes` TEXT,
  `TipAmount` DECIMAL(14,4) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `UnfillNotification` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `UserNotifiedPreBooking` VARCHAR(512) NULL,
  `UserNotifiedPreBookingEmail` VARCHAR(512) NULL,
  `Value` DECIMAL(14,4) NULL,
  `YYYY` VARCHAR(512) NULL,
  `Zip` VARCHAR(512) NULL,
  `searchAdrress` VARCHAR(512) NULL,
  PRIMARY KEY (`BookingId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingExtra` (
  `BookingExtraId` INT NOT NULL AUTO_INCREMENT,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookedBy` VARCHAR(512) NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `CSNotes` TEXT,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `CheckOutTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `ColorCode` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `DOB` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `RealFinishTime` DATETIME NULL,
  `RealStartTime` DATETIME NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffId` INT NULL,
  `StaffNotes` TEXT,
  `StaffVacConflict` VARCHAR(512) NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `Therapist` VARCHAR(512) NULL,
  `TherapistNotes` TEXT,
  `TipAmount` DECIMAL(14,4) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `UnfillNotification` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Value` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`BookingExtraId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProduct` (
  `BookingProductId` INT NOT NULL AUTO_INCREMENT,
  `AcceptedOn` VARCHAR(512) NULL,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `BookedBy` VARCHAR(512) NULL,
  `BookingAddOnPaymentId` INT NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductAddOnId` INT NULL,
  `BookingProductStatus` VARCHAR(512) NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `BookingTipId` INT NULL,
  `CSNotes` TEXT,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `CheckOutTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `ColorCode` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurrentBookingId` INT NULL,
  `DOB` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DiffAccepted` VARCHAR(512) NULL,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraAddOn` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `FcmToken` TEXT,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `ForceStaffAllot` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `RealFinishTime` DATETIME NULL,
  `RealStartTime` DATETIME NULL,
  `RequestStatus` VARCHAR(512) NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffId` INT NULL,
  `StaffNotes` TEXT,
  `StaffVacConflict` VARCHAR(512) NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `SystemPhase` VARCHAR(512) NULL,
  `Therapist` VARCHAR(512) NULL,
  `TherapistNotes` TEXT,
  `TipAmount` DECIMAL(14,4) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `UnfillNotification` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Value` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  `diffAccepted` VARCHAR(512) NULL,
  `guestId` INT NULL,
  `userId` INT NULL,
  PRIMARY KEY (`BookingProductId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProductAddOn` (
  `BookingProductAddOnId` INT NOT NULL AUTO_INCREMENT,
  `ACCEPTED` VARCHAR(512) NULL,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAccepted` VARCHAR(512) NULL,
  `BookedBy` VARCHAR(512) NULL,
  `BookingAddOnPaymentId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `CSNotes` TEXT,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `CheckOutTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `ColorCode` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurrentBookingId` INT NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EventId` INT NULL,
  `ExtraAddOn` VARCHAR(512) NULL,
  `ExtraNotified` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `FcmToken` TEXT,
  `Floor` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `ReachOutTime` DATETIME NULL,
  `RealFinishTime` DATETIME NULL,
  `RealStartTime` DATETIME NULL,
  `RequestStatus` VARCHAR(512) NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffId` INT NULL,
  `StaffNotes` TEXT,
  `StaffVacConflict` VARCHAR(512) NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `TherapistNotes` TEXT,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`BookingProductAddOnId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProductExtra` (
  `BookingProductExtraId` INT NOT NULL AUTO_INCREMENT,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookedBy` VARCHAR(512) NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductAddOnId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `DOB` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraAddOn` VARCHAR(512) NULL,
  `ExtraTitle` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `RequestStatus` VARCHAR(512) NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffId` INT NULL,
  `StaffVacConflict` VARCHAR(512) NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `Therapist` VARCHAR(512) NULL,
  `TipAmount` DECIMAL(14,4) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Value` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`BookingProductExtraId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProductDispatch` (
  `BookingProductDispatchId` INT NOT NULL AUTO_INCREMENT,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookingId` INT NULL,
  `BookingProductAddOnId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProductStatus` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `ExtraAddOn` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `FcmToken` TEXT,
  `Floor` VARCHAR(512) NULL,
  `Gender` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `OrganisationLocationId` INT NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `ReachOutTime` DATETIME NULL,
  `RequestStatus` VARCHAR(512) NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffId` INT NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`BookingProductDispatchId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingAddOnPayment` (
  `BookingAddOnPaymentId` INT NOT NULL AUTO_INCREMENT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookingId` INT NULL,
  `BookingTipId` INT NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `PaymentIntent` VARCHAR(512) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`BookingAddOnPaymentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingPreference` (
  `BookingPreferenceId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `GlobalDispatchDefault` VARCHAR(512) NULL,
  `InstantConfirmation` VARCHAR(512) NULL,
  `IsFilterApplied` VARCHAR(512) NULL,
  `IsPriorityActive` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`BookingPreferenceId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `DispatchFilter` (
  `DispatchFilterId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `IsActive` VARCHAR(512) NULL,
  `IsUsedInFilter` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Priority` VARCHAR(512) NULL,
  `StaffGroupId` INT NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`DispatchFilterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingTip` (
  `BookingTipId` INT NOT NULL AUTO_INCREMENT,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookedBy` VARCHAR(512) NULL,
  `BookingAddOnPaymentId` INT NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `DOB` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `SameTime` DATETIME NULL,
  `StaffId` INT NULL,
  `StaffVacConflict` VARCHAR(512) NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `Therapist` VARCHAR(512) NULL,
  `TipAmount` DECIMAL(14,4) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Value` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`BookingTipId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Category` (
  `CategoryId` INT NOT NULL AUTO_INCREMENT,
  `AddOnCategoryId` INT NULL,
  `AddOnId` INT NULL,
  `Address` TEXT,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `AppleIdentifier` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `AverageRating` VARCHAR(512) NULL,
  `BookedBy` VARCHAR(512) NULL,
  `BookingId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `COCONRating` VARCHAR(512) NULL,
  `CSNotes` TEXT,
  `City` VARCHAR(512) NULL,
  `ColorCode` VARCHAR(512) NULL,
  `CompanyName` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `DeviceId` INT NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EndTime` DATETIME NULL,
  `ExtraTitle` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Floor` VARCHAR(512) NULL,
  `FridayRate` DECIMAL(14,4) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `IbanNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `IsAddEditScheduleEnable` VARCHAR(512) NULL,
  `KvkNumber` VARCHAR(512) NULL,
  `LanguageId` INT NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `MondayRate` DECIMAL(14,4) NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductDurationId` INT NULL,
  `ProductExtraId` INT NULL,
  `ProductExtraMaxSelect` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `ProductTranslationId` INT NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `Rank` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `SaturdayRate` DECIMAL(14,4) NULL,
  `Sequence` VARCHAR(512) NULL,
  `ShowOutsideOffers` VARCHAR(512) NULL,
  `StaffCategoryId` INT NULL,
  `StaffGroupId` INT NULL,
  `StaffId` INT NULL,
  `StaffProductId` INT NULL,
  `StaffType` VARCHAR(512) NULL,
  `StaffVacConflict` VARCHAR(512) NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `SundayRate` DECIMAL(14,4) NULL,
  `TherapistNotes` TEXT,
  `ThursdayRate` DECIMAL(14,4) NULL,
  `TipReceived` DECIMAL(14,4) NULL,
  `TotalRatings` DECIMAL(14,4) NULL,
  `TuesdayRate` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `WednesdayRate` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`CategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Center` (
  `CenterId` INT NOT NULL AUTO_INCREMENT,
  `Address` TEXT,
  `Archive` INT NULL DEFAULT 0,
  `CheckInProximity` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Latitude` DECIMAL(14,4) NULL,
  `Longitude` DECIMAL(14,4) NULL,
  `Name` VARCHAR(512) NULL,
  `ServiceArea` VARCHAR(512) NULL,
  `SosContact` VARCHAR(512) NULL,
  `SosContactSecondary` VARCHAR(512) NULL,
  `TodayLeadTime` DATETIME NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`CenterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SpecialRequest` (
  `SpecialRequestId` INT NOT NULL AUTO_INCREMENT,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `AdminNotes` TEXT,
  `Archive` INT NULL DEFAULT 0,
  `BookingExtraId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductAddOnId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `CheckOutTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `Gender` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `OrganisationLocationId` INT NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `ReachOutTime` DATETIME NULL,
  `RealFinishTime` DATETIME NULL,
  `RealStartTime` DATETIME NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffId` INT NULL,
  `StaffNotes` TEXT,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`SpecialRequestId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Faq` (
  `FaqId` INT NOT NULL AUTO_INCREMENT,
  `Answer` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Question` VARCHAR(512) NULL,
  `SectionId` INT NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`FaqId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FaqSection` (
  `FaqSectionId` INT NOT NULL AUTO_INCREMENT,
  `Answer` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `FaqId` INT NULL,
  `LastUpdated` DATETIME NULL,
  `Question` VARCHAR(512) NULL,
  `SectionId` INT NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`FaqSectionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Guest` (
  `GuestId` INT NOT NULL AUTO_INCREMENT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookingId` INT NULL,
  `CategoryId` INT NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `ForceStaffAllot` VARCHAR(512) NULL,
  `Gender` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Relation` DECIMAL(14,4) NULL,
  `SameTime` DATETIME NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffId` INT NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Therapist` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`GuestId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GuestUser` (
  `GuestUserId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DeviceId` INT NULL,
  `FcmToken` TEXT,
  `LastUpdated` DATETIME NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`GuestUserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Language` (
  `LanguageId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`LanguageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `LocationRequest` (
  `LocationRequestId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Distance` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Latitude` DECIMAL(14,4) NULL,
  `Longitude` DECIMAL(14,4) NULL,
  `Name` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `UserName` VARCHAR(512) NULL,
  `ascending` VARCHAR(512) NULL,
  PRIMARY KEY (`LocationRequestId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Message` (
  `MessageId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Title` VARCHAR(512) NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `ascending` VARCHAR(512) NULL,
  PRIMARY KEY (`MessageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Product` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `AddOnCategoryId` INT NULL,
  `AddOnId` INT NULL,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `CategoryId` INT NULL,
  `ColorCode` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `Duration` VARCHAR(512) NULL,
  `ExtraTitle` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LanguageId` INT NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `PreparationTime` DATETIME NULL,
  `ProductDurationId` INT NULL,
  `ProductExtraId` INT NULL,
  `ProductExtraMaxSelect` VARCHAR(512) NULL,
  `ProductTranslationId` INT NULL,
  `StaffGroupId` INT NULL,
  `StaffId` INT NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`ProductId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ProductDuration` (
  `ProductDurationId` INT NOT NULL AUTO_INCREMENT,
  `AddOnCategoryId` INT NULL,
  `AddOnId` INT NULL,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `CategoryId` INT NULL,
  `ColorCode` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `Duration` VARCHAR(512) NULL,
  `ExtraTitle` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LanguageId` INT NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `PreparationTime` DATETIME NULL,
  `ProductExtraId` INT NULL,
  `ProductExtraMaxSelect` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `ProductTranslationId` INT NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`ProductDurationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ProductExtra` (
  `ProductExtraId` INT NOT NULL AUTO_INCREMENT,
  `AddOnCategoryId` INT NULL,
  `AddOnId` INT NULL,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `CategoryId` INT NULL,
  `ColorCode` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `Duration` VARCHAR(512) NULL,
  `ExtraTitle` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LanguageId` INT NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `PreparationTime` DATETIME NULL,
  `ProductDurationId` INT NULL,
  `ProductExtraMaxSelect` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `ProductTranslationId` INT NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`ProductExtraId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ProductTranslation` (
  `ProductTranslationId` INT NOT NULL AUTO_INCREMENT,
  `AddOnCategoryId` INT NULL,
  `AddOnId` INT NULL,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `CategoryId` INT NULL,
  `ColorCode` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `Duration` VARCHAR(512) NULL,
  `ExtraTitle` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LanguageId` INT NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `PreparationTime` DATETIME NULL,
  `ProductDurationId` INT NULL,
  `ProductExtraId` INT NULL,
  `ProductExtraMaxSelect` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`ProductTranslationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PromoCode` (
  `PromoCodeId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `BookingId` INT NULL,
  `CategoryId` INT NULL,
  `Class` VARCHAR(512) NULL,
  `Code` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurrentCount` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `EndDate` DATETIME NULL,
  `LastUpdated` DATETIME NULL,
  `MaxAmount` DECIMAL(14,4) NULL,
  `MinPurchaseAmount` DECIMAL(14,4) NULL,
  `Mode` VARCHAR(512) NULL,
  `PrmocodeId` INT NULL,
  `RedeemCount` VARCHAR(512) NULL,
  `StartDate` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `Value` DECIMAL(14,4) NULL,
  PRIMARY KEY (`PromoCodeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PromoCodeCategory` (
  `PromoCodeCategoryId` INT NOT NULL AUTO_INCREMENT,
  `AGPromoCodeId` INT NULL,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookingAddOnPaymentId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductId` INT NULL,
  `CategoryId` INT NULL,
  `Class` VARCHAR(512) NULL,
  `Code` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurrentCount` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Duration` VARCHAR(512) NULL,
  `EndDate` DATETIME NULL,
  `LastUpdated` DATETIME NULL,
  `MaxAmount` DECIMAL(14,4) NULL,
  `MinPurchaseAmount` DECIMAL(14,4) NULL,
  `Mode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `RedeemCount` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StartDate` DATETIME NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `Value` DECIMAL(14,4) NULL,
  PRIMARY KEY (`PromoCodeCategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Rating` (
  `RatingId` INT NOT NULL AUTO_INCREMENT,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookedBy` VARCHAR(512) NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `DOB` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `SameTime` DATETIME NULL,
  `StaffId` INT NULL,
  `StaffVacConflict` VARCHAR(512) NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `Therapist` VARCHAR(512) NULL,
  `TipAmount` DECIMAL(14,4) NULL,
  `TotalRating` DECIMAL(14,4) NULL,
  `TotalTip` DECIMAL(14,4) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Value` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`RatingId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Section` (
  `SectionId` INT NOT NULL AUTO_INCREMENT,
  `Answer` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `FaqId` INT NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Question` VARCHAR(512) NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`SectionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Staff` (
  `StaffId` INT NOT NULL AUTO_INCREMENT,
  `Address` TEXT,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `AppleIdentifier` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `AverageRating` VARCHAR(512) NULL,
  `BookedBy` VARCHAR(512) NULL,
  `BookingAddOnPaymentId` INT NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingTipId` INT NULL,
  `COCONRating` VARCHAR(512) NULL,
  `CSNotes` TEXT,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `ColorCode` VARCHAR(512) NULL,
  `CompanyName` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurrentBookingId` INT NULL,
  `DOB` DATETIME NULL,
  `Date` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `DayCount` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `DeviceId` INT NULL,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EndTime` DATETIME NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `IbanNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `IsAddEditScheduleEnable` VARCHAR(512) NULL,
  `KvkNumber` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `Password` VARCHAR(255) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `Rank` VARCHAR(512) NULL,
  `Rate` DECIMAL(14,4) NULL,
  `ReachOutTime` DATETIME NULL,
  `RefreshToken` TEXT,
  `RequestId` INT NULL,
  `SameTime` DATETIME NULL,
  `Sequence` VARCHAR(512) NULL,
  `ShowOutsideOffers` VARCHAR(512) NULL,
  `StaffCategoryId` INT NULL,
  `StaffGroupId` INT NULL,
  `StaffMessageId` INT NULL,
  `StaffProductId` INT NULL,
  `StaffType` VARCHAR(512) NULL,
  `StaffVacConflict` VARCHAR(512) NULL,
  `StaffVacationId` INT NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `SystemPhase` VARCHAR(512) NULL,
  `Tag` VARCHAR(512) NULL,
  `Template` DECIMAL(14,4) NULL,
  `Therapist` VARCHAR(512) NULL,
  `TherapistNotes` TEXT,
  `TipAmount` DECIMAL(14,4) NULL,
  `TipReceived` DECIMAL(14,4) NULL,
  `Title` VARCHAR(512) NULL,
  `TotalRatings` DECIMAL(14,4) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Value` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  `max_seq` VARCHAR(512) NULL,
  PRIMARY KEY (`StaffId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffBlockTime` (
  `StaffBlockTimeId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `BlocKTimeId` INT NULL,
  `BlockTimeId` INT NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `EndTime` DATETIME NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `ScheduleType` VARCHAR(512) NULL,
  `StaffBlocKTimeId` INT NULL,
  `StaffId` INT NULL,
  `StaffScheduleId` INT NULL,
  `StartTime` DATETIME NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`StaffBlockTimeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffCategory` (
  `StaffCategoryId` INT NOT NULL AUTO_INCREMENT,
  `Address` TEXT,
  `AppleIdentifier` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `AverageRating` VARCHAR(512) NULL,
  `COCONRating` VARCHAR(512) NULL,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `CompanyName` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DeviceId` INT NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `IbanNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `IsAddEditScheduleEnable` VARCHAR(512) NULL,
  `KvkNumber` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `ProductId` INT NULL,
  `Rank` VARCHAR(512) NULL,
  `Rate` DECIMAL(14,4) NULL,
  `Sequence` VARCHAR(512) NULL,
  `ShowOutsideOffers` VARCHAR(512) NULL,
  `StaffGroupId` INT NULL,
  `StaffId` INT NULL,
  `StaffProductId` INT NULL,
  `StaffType` VARCHAR(512) NULL,
  `Status` VARCHAR(512) NULL,
  `TipReceived` DECIMAL(14,4) NULL,
  `TotalRatings` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`StaffCategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffMessage` (
  `StaffMessageId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Date` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `FcmToken` TEXT,
  `ImagePath` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `StaffId` INT NULL,
  `Tag` VARCHAR(512) NULL,
  `Title` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`StaffMessageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffVacation` (
  `StaffVacationId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `DayCount` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `EndTime` DATETIME NULL,
  `EventId` INT NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `RequestId` INT NULL,
  `StaffId` INT NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Template` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`StaffVacationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffSchedule` (
  `StaffScheduleId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `BlocKTimeId` INT NULL,
  `BlockTimeId` INT NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `EndTime` DATETIME NULL,
  `Friday` VARCHAR(512) NULL,
  `FridayBlockTimeId` INT NULL,
  `FridayEndDate` DATETIME NULL,
  `FridayEndTime` DATETIME NULL,
  `FridayStartDate` DATETIME NULL,
  `FridayStartTime` DATETIME NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Monday` VARCHAR(512) NULL,
  `MondayBlockTimeId` INT NULL,
  `MondayEndDate` DATETIME NULL,
  `MondayEndTime` DATETIME NULL,
  `MondayStartDate` DATETIME NULL,
  `MondayStartTime` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Saturday` VARCHAR(512) NULL,
  `SaturdayBlockTimeId` INT NULL,
  `SaturdayEndDate` DATETIME NULL,
  `SaturdayEndTime` DATETIME NULL,
  `SaturdayStartDate` DATETIME NULL,
  `SaturdayStartTime` DATETIME NULL,
  `ScheduleType` VARCHAR(512) NULL,
  `StaffBlocKTimeId` INT NULL,
  `StaffId` INT NULL,
  `StartTime` DATETIME NULL,
  `Sunday` VARCHAR(512) NULL,
  `SundayBlockTimeId` INT NULL,
  `SundayEndDate` DATETIME NULL,
  `SundayEndTime` DATETIME NULL,
  `SundayStartDate` DATETIME NULL,
  `SundayStartTime` DATETIME NULL,
  `Thursday` VARCHAR(512) NULL,
  `ThursdayBlockTimeId` INT NULL,
  `ThursdayEndDate` DATETIME NULL,
  `ThursdayEndTime` DATETIME NULL,
  `ThursdayStartDate` DATETIME NULL,
  `ThursdayStartTime` DATETIME NULL,
  `Tuesday` VARCHAR(512) NULL,
  `TuesdayBlockTimeId` INT NULL,
  `TuesdayEndDate` DATETIME NULL,
  `TuesdayEndTime` DATETIME NULL,
  `TuesdayStartDate` DATETIME NULL,
  `TuesdayStartTime` DATETIME NULL,
  `Updated` DATETIME NULL,
  `Wednesday` VARCHAR(512) NULL,
  `WednesdayBlockTimeId` INT NULL,
  `WednesdayEndDate` DATETIME NULL,
  `WednesdayEndTime` DATETIME NULL,
  `WednesdayStartDate` DATETIME NULL,
  `WednesdayStartTime` DATETIME NULL,
  PRIMARY KEY (`StaffScheduleId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffRegistration` (
  `StaffRegistrationId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `IsRegCodeUsed` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `RegistrationCode` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`StaffRegistrationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffGroup` (
  `StaffGroupId` INT NOT NULL AUTO_INCREMENT,
  `Address` TEXT,
  `AppleIdentifier` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `AverageRating` VARCHAR(512) NULL,
  `COCONRating` VARCHAR(512) NULL,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `CompanyName` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DeviceId` INT NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `IbanNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `IsActive` VARCHAR(512) NULL,
  `IsAddEditScheduleEnable` VARCHAR(512) NULL,
  `IsUsedInFilter` VARCHAR(512) NULL,
  `KvkNumber` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `Priority` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Rank` VARCHAR(512) NULL,
  `Rate` DECIMAL(14,4) NULL,
  `Sequence` VARCHAR(512) NULL,
  `ShowOutsideOffers` VARCHAR(512) NULL,
  `StaffCategoryId` INT NULL,
  `StaffId` INT NULL,
  `StaffProductId` INT NULL,
  `StaffType` VARCHAR(512) NULL,
  `Status` VARCHAR(512) NULL,
  `TipReceived` DECIMAL(14,4) NULL,
  `TotalRatings` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`StaffGroupId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffProduct` (
  `StaffProductId` INT NOT NULL AUTO_INCREMENT,
  `Address` TEXT,
  `AppleIdentifier` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `AverageRating` VARCHAR(512) NULL,
  `COCONRating` VARCHAR(512) NULL,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `CompanyName` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DeviceId` INT NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `IbanNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `IsAddEditScheduleEnable` VARCHAR(512) NULL,
  `KvkNumber` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `ProductId` INT NULL,
  `Rank` VARCHAR(512) NULL,
  `Rate` DECIMAL(14,4) NULL,
  `Sequence` VARCHAR(512) NULL,
  `ShowOutsideOffers` VARCHAR(512) NULL,
  `StaffCategoryId` INT NULL,
  `StaffGroupId` INT NULL,
  `StaffId` INT NULL,
  `StaffType` VARCHAR(512) NULL,
  `Status` VARCHAR(512) NULL,
  `TipReceived` DECIMAL(14,4) NULL,
  `TotalRatings` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`StaffProductId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffMetadata` (
  `StaffMetadataId` INT NOT NULL AUTO_INCREMENT,
  `Address` TEXT,
  `AppleIdentifier` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `AverageRating` VARCHAR(512) NULL,
  `BookingProductId` INT NULL,
  `COCONRating` VARCHAR(512) NULL,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `CompanyName` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DeviceId` INT NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `IbanNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `IsAddEditScheduleEnable` VARCHAR(512) NULL,
  `KvkNumber` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `ProductId` INT NULL,
  `Rank` VARCHAR(512) NULL,
  `Rate` DECIMAL(14,4) NULL,
  `Sequence` VARCHAR(512) NULL,
  `ShowOutsideOffers` VARCHAR(512) NULL,
  `StaffCategoryId` INT NULL,
  `StaffGroupId` INT NULL,
  `StaffId` INT NULL,
  `StaffProductId` INT NULL,
  `StaffType` VARCHAR(512) NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `TipReceived` DECIMAL(14,4) NULL,
  `TotalRatings` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`StaffMetadataId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SosContact` (
  `SosContactId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`SosContactId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `AppleId` INT NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookedBy` VARCHAR(512) NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductAddOnId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `BookingTipId` INT NULL,
  `CSNotes` TEXT,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `ColorCode` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurrentBookingId` INT NULL,
  `CustomerId` INT NULL,
  `DOB` DATETIME NULL,
  `Date` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `DeviceId` INT NULL,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraAddOn` VARCHAR(512) NULL,
  `ExtraNotified` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `GuestId` INT NULL,
  `GuestUserId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `IsCalPermitted` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Latitude` DECIMAL(14,4) NULL,
  `LocationRequestId` INT NULL,
  `Longitude` DECIMAL(14,4) NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrganisationLocationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `Password` VARCHAR(255) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `RatingId` INT NULL,
  `ReachOutTime` DATETIME NULL,
  `RefreshToken` TEXT,
  `RequestStatus` VARCHAR(512) NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffId` INT NULL,
  `StaffVacConflict` VARCHAR(512) NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `Therapist` VARCHAR(512) NULL,
  `TherapistNotes` TEXT,
  `TipAmount` DECIMAL(14,4) NULL,
  `Title` VARCHAR(512) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `UnfillNotification` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserMessageId` INT NULL,
  `UserName` VARCHAR(512) NULL,
  `UserNotifiedPreBooking` VARCHAR(512) NULL,
  `UserNotifiedPreBookingEmail` VARCHAR(512) NULL,
  `Value` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  `ascending` VARCHAR(512) NULL,
  PRIMARY KEY (`UserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `UserMessage` (
  `UserMessageId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Date` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `FcmToken` TEXT,
  `ImagePath` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Title` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`UserMessageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AccountDeleteFeedback` (
  `AccountDeleteFeedbackId` INT NOT NULL AUTO_INCREMENT,
  `AppleId` INT NULL,
  `Archive` INT NULL DEFAULT 0,
  `CSNotes` TEXT,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CustomerId` INT NULL,
  `DOB` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `FacebookId` INT NULL,
  `Feedback` DECIMAL(14,4) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `IsCalPermitted` VARCHAR(512) NULL,
  `IssueType` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Latitude` DECIMAL(14,4) NULL,
  `Longitude` DECIMAL(14,4) NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `PreferredLanguage` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `Street` VARCHAR(512) NULL,
  `Therapist` VARCHAR(512) NULL,
  `TherapistNotes` TEXT,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`AccountDeleteFeedbackId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingSpecialRequest` (
  `BookingSpecialRequestId` INT NOT NULL AUTO_INCREMENT,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `Archive` INT NULL DEFAULT 0,
  `BookingAddOnPaymentId` INT NULL,
  `BookingExtraId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductAddOnId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `CheckOutTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurrentCount` VARCHAR(512) NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `Gender` VARCHAR(512) NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `OrganisationLocationId` INT NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `PromoCodeId` INT NULL,
  `ReachOutTime` DATETIME NULL,
  `RealFinishTime` DATETIME NULL,
  `RealStartTime` DATETIME NULL,
  `SameTime` DATETIME NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffId` INT NULL,
  `StaffNotes` TEXT,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`BookingSpecialRequestId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingChannel` (
  `BookingChannelId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`BookingChannelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingInvoiceData` (
  `BookingInvoiceDataId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `BookingId` INT NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `InvoiceEmail` VARCHAR(512) NULL,
  `InvoiceId` INT NULL,
  `InvoiceStripeStatus` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Updated` DATETIME NULL,
  `open` VARCHAR(512) NULL,
  PRIMARY KEY (`BookingInvoiceDataId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Organisation` (
  `OrganisationId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `BusinessTypeId` INT NULL,
  `City` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `ContactNumber` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Distance` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `Floor` VARCHAR(512) NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrgLoc` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `ProfileImagePath` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `Street` VARCHAR(512) NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`OrganisationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `OrganisationLocation` (
  `OrganisationLocationId` INT NOT NULL AUTO_INCREMENT,
  `AddOn` VARCHAR(512) NULL,
  `AddOnId` INT NULL,
  `Address` TEXT,
  `AdminId` INT NULL,
  `AdminNotes` TEXT,
  `Amount` DECIMAL(14,4) NULL,
  `AppleIdentifier` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `AverageRating` VARCHAR(512) NULL,
  `BookedBy` VARCHAR(512) NULL,
  `BookingBusinessType` VARCHAR(512) NULL,
  `BookingChannelId` INT NULL,
  `BookingId` INT NULL,
  `BookingProductAddOnId` INT NULL,
  `BookingProductId` INT NULL,
  `BookingProvider` VARCHAR(512) NULL,
  `BookingSpecialRequestId` INT NULL,
  `BusinessTypeId` INT NULL,
  `COCONRating` VARCHAR(512) NULL,
  `CSNotes` TEXT,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `CategoryId` INT NULL,
  `CheckInTime` DATETIME NULL,
  `CheckOutTime` DATETIME NULL,
  `City` VARCHAR(512) NULL,
  `ClientSource` VARCHAR(512) NULL,
  `CoconNotes` TEXT,
  `ColorCode` VARCHAR(512) NULL,
  `CompanyName` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `ContactNumber` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `DOB` DATETIME NULL,
  `DateTime` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `DeviceId` INT NULL,
  `Discount` DECIMAL(14,4) NULL,
  `DiscountedAmount` DECIMAL(14,4) NULL,
  `DispatchId` INT NULL,
  `DispatchType` VARCHAR(512) NULL,
  `Distance` VARCHAR(512) NULL,
  `Duration` VARCHAR(512) NULL,
  `EaseOfBooking` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `EncryptedOrganisationLocationId` INT NULL,
  `EventId` INT NULL,
  `Experience` VARCHAR(512) NULL,
  `ExtraAddOn` VARCHAR(512) NULL,
  `ExtraTitle` VARCHAR(512) NULL,
  `ExtraValue` DECIMAL(14,4) NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Feedback` DECIMAL(14,4) NULL,
  `Floor` VARCHAR(512) NULL,
  `FromCMS` VARCHAR(512) NULL,
  `FullAddress` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `GuestId` INT NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `IbanNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `InvoiceUrl` VARCHAR(512) NULL,
  `IsAddEditScheduleEnable` VARCHAR(512) NULL,
  `KvkNumber` VARCHAR(512) NULL,
  `LanguageId` INT NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `Notes` TEXT,
  `OrgLoc` VARCHAR(512) NULL,
  `OrganisationId` INT NULL,
  `PaidPrice` DECIMAL(14,4) NULL,
  `PaymentStatus` VARCHAR(512) NULL,
  `PaymentType` VARCHAR(512) NULL,
  `PredecessorBookingId` INT NULL,
  `PreferredLanguage` VARCHAR(512) NULL,
  `PreparationTime` DATETIME NULL,
  `Product` VARCHAR(512) NULL,
  `ProductExtraMaxSelect` VARCHAR(512) NULL,
  `ProductId` INT NULL,
  `Professionalism` VARCHAR(512) NULL,
  `ProfileImagePath` VARCHAR(512) NULL,
  `PromoAmount` DECIMAL(14,4) NULL,
  `PromoCode` VARCHAR(512) NULL,
  `PromoCodeId` INT NULL,
  `Quality` VARCHAR(512) NULL,
  `Rank` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `RealFinishTime` DATETIME NULL,
  `RealStartTime` DATETIME NULL,
  `RequestStatus` VARCHAR(512) NULL,
  `SameTime` DATETIME NULL,
  `Sequence` VARCHAR(512) NULL,
  `ShowOutsideOffers` VARCHAR(512) NULL,
  `SpecialRequestId` INT NULL,
  `SpecialRequestName` VARCHAR(512) NULL,
  `StaffAmount` DECIMAL(14,4) NULL,
  `StaffCategoryId` INT NULL,
  `StaffEarning` VARCHAR(512) NULL,
  `StaffGroupId` INT NULL,
  `StaffId` INT NULL,
  `StaffNotes` TEXT,
  `StaffProductId` INT NULL,
  `StaffType` VARCHAR(512) NULL,
  `StaffVacConflict` VARCHAR(512) NULL,
  `StartTime` DATETIME NULL,
  `Status` VARCHAR(512) NULL,
  `Street` VARCHAR(512) NULL,
  `SuccessorBookingId` INT NULL,
  `Therapist` VARCHAR(512) NULL,
  `TherapistNotes` TEXT,
  `TipAmount` DECIMAL(14,4) NULL,
  `TipReceived` DECIMAL(14,4) NULL,
  `TotalRatings` DECIMAL(14,4) NULL,
  `TransactionDate` DATETIME NULL,
  `TransactionId` INT NULL,
  `TravelFee` DECIMAL(14,4) NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `UserId` INT NULL,
  `Value` DECIMAL(14,4) NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`OrganisationLocationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BusinessType` (
  `BusinessTypeId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `City` VARCHAR(512) NULL,
  `Cocon` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `ContactNumber` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Distance` VARCHAR(512) NULL,
  `Elevator` VARCHAR(512) NULL,
  `Email` VARCHAR(512) NULL,
  `Floor` VARCHAR(512) NULL,
  `HouseNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrgLoc` VARCHAR(512) NULL,
  `OrganisationId` INT NULL,
  `OrganisationLocationId` INT NULL,
  `ProfileImagePath` VARCHAR(512) NULL,
  `ReachOutTime` DATETIME NULL,
  `Street` VARCHAR(512) NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`BusinessTypeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffOrganisation` (
  `StaffOrganisationId` INT NOT NULL AUTO_INCREMENT,
  `Address` TEXT,
  `AppleIdentifier` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `AutoAcceptAddonRequest` VARCHAR(512) NULL,
  `AverageRating` VARCHAR(512) NULL,
  `COCONRating` VARCHAR(512) NULL,
  `CategoryId` INT NULL,
  `City` VARCHAR(512) NULL,
  `CompanyName` VARCHAR(512) NULL,
  `Contact` VARCHAR(512) NULL,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `DeviceId` INT NULL,
  `FacebookId` INT NULL,
  `FcmToken` TEXT,
  `Gender` VARCHAR(512) NULL,
  `GoogleEmail` VARCHAR(512) NULL,
  `GoogleId` INT NULL,
  `IbanNumber` VARCHAR(512) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `IsAddEditScheduleEnable` VARCHAR(512) NULL,
  `KvkNumber` VARCHAR(512) NULL,
  `LastMessageRead` TEXT,
  `LastUpdated` DATETIME NULL,
  `Name` VARCHAR(512) NULL,
  `OrganisationLocationId` INT NULL,
  `ProductId` INT NULL,
  `Rank` VARCHAR(512) NULL,
  `Rate` DECIMAL(14,4) NULL,
  `Sequence` VARCHAR(512) NULL,
  `ShowOutsideOffers` VARCHAR(512) NULL,
  `StaffCategoryId` INT NULL,
  `StaffGroupId` INT NULL,
  `StaffId` INT NULL,
  `StaffProductId` INT NULL,
  `StaffType` VARCHAR(512) NULL,
  `Status` VARCHAR(512) NULL,
  `TipReceived` DECIMAL(14,4) NULL,
  `TotalRatings` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `Zip` VARCHAR(512) NULL,
  PRIMARY KEY (`StaffOrganisationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingInstructions` (
  `BookingInstructionsId` INT NOT NULL AUTO_INCREMENT,
  `AVAILABILITY` VARCHAR(512) NULL,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Type` VARCHAR(512) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`BookingInstructionsId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ActionsLog` (
  `ActionsLogId` INT NOT NULL AUTO_INCREMENT,
  `ActionType` INT NULL,
  `AdminId` INT NULL,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `TableId` INT NULL,
  `TableName` VARCHAR(255) NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`ActionsLogId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffAccountDeleteFeedback` (
  `StaffAccountDeleteFeedbackId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Feedback` DECIMAL(14,4) NULL,
  `IssueType` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `StaffId` INT NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`StaffAccountDeleteFeedbackId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ServiceZipCode` (
  `ServiceZipCodeId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Updated` DATETIME NULL,
  `Zipcode` VARCHAR(512) NULL,
  PRIMARY KEY (`ServiceZipCodeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CategoryHourlyRate` (
  `CategoryHourlyRateId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `CategoryId` INT NULL,
  `Created` DATETIME NULL,
  `CurOrder` VARCHAR(512) NULL,
  `Deleted` INT NULL DEFAULT 0,
  `Description` TEXT,
  `EndTime` DATETIME NULL,
  `FridayRate` DECIMAL(14,4) NULL,
  `ImagePath` VARCHAR(512) NULL,
  `LastUpdated` DATETIME NULL,
  `MondayRate` DECIMAL(14,4) NULL,
  `Name` VARCHAR(512) NULL,
  `SaturdayRate` DECIMAL(14,4) NULL,
  `StartTime` DATETIME NULL,
  `SundayRate` DECIMAL(14,4) NULL,
  `ThursdayRate` DECIMAL(14,4) NULL,
  `TuesdayRate` DECIMAL(14,4) NULL,
  `Updated` DATETIME NULL,
  `WednesdayRate` DECIMAL(14,4) NULL,
  PRIMARY KEY (`CategoryHourlyRateId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProductAppliedRate` (
  `BookingProductAppliedRateId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT NULL DEFAULT 0,
  `Created` DATETIME NULL,
  `Deleted` INT NULL DEFAULT 0,
  `LastUpdated` DATETIME NULL,
  `Updated` DATETIME NULL,
  PRIMARY KEY (`BookingProductAppliedRateId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=1;
