-- =====================================================================
-- COCON Backend API - reverse-engineered MySQL schema
-- Generated from Knex query references in src/ (schema/migrations absent).
-- All non-PK columns are NULLable; no FKs/NOT NULL so inserts never break.
-- Charset utf8mb4. Column identifiers are backtick-quoted.
-- =====================================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `AddOn` (
  `AddOnId` INT NOT NULL AUTO_INCREMENT,
  `Amount` DECIMAL(12,4) DEFAULT NULL,
  `CurOrder` INT DEFAULT NULL,
  `Deleted` INT DEFAULT 0,
  `Duration` INT DEFAULT NULL,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`AddOnId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AddOnCategory` (
  `AddOnCategoryId` INT NOT NULL AUTO_INCREMENT,
  `AddOnId` INT DEFAULT NULL,
  `CategoryId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`AddOnCategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Admin` (
  `AdminId` INT NOT NULL AUTO_INCREMENT,
  `Contact` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `Deleted` INT DEFAULT 0,
  `Email` VARCHAR(255) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `OrganisationLocationId` INT DEFAULT NULL,
  `ProfileImagePath` VARCHAR(255) DEFAULT NULL,
  `Password` VARCHAR(255) DEFAULT NULL,
  `Type` INT DEFAULT 0,
  PRIMARY KEY (`AdminId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AdminNotificationContact` (
  `AdminNotificationContactId` INT NOT NULL AUTO_INCREMENT,
  `Deleted` INT DEFAULT 0,
  `Type` INT DEFAULT 0,
  `Value` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`AdminNotificationContactId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AppVersion` (
  `AppVersionId` INT NOT NULL AUTO_INCREMENT,
  `Type` INT DEFAULT 0,
  `Platform` VARCHAR(255) DEFAULT NULL,
  `Version` VARCHAR(255) DEFAULT NULL,
  `IsForceUpdate` INT DEFAULT 0,
  `IsActive` INT DEFAULT 0,
  `UseEncryption` INT DEFAULT 0,
  `MaintenanceMessage` TEXT,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`AppVersionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Bank` (
  `BankId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL,
  `BankKey` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BankId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Booking` (
  `BookingId` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT DEFAULT NULL,
  `Amount` DECIMAL(12,4) DEFAULT NULL,
  `BookedBy` INT DEFAULT 0,
  `BookingBusinessType` INT DEFAULT 0,
  `BookingChannelId` INT DEFAULT NULL,
  `BookingProvider` INT DEFAULT NULL,
  `CancelBookingNotes` TEXT,
  `CancelBookingReason` TEXT,
  `City` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `DateTime` DATETIME DEFAULT NULL,
  `Deleted` INT DEFAULT 0,
  `Distance` DECIMAL(12,4) DEFAULT NULL,
  `Duration` INT DEFAULT NULL,
  `Elevator` INT DEFAULT 0,
  `Floor` VARCHAR(255) DEFAULT NULL,
  `FullAddress` VARCHAR(255) DEFAULT NULL,
  `HouseNumber` VARCHAR(255) DEFAULT NULL,
  `InvoiceUrl` VARCHAR(255) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `OrganisationLocationId` INT DEFAULT NULL,
  `PaidPrice` DECIMAL(12,4) DEFAULT NULL,
  `PaymentStatus` INT DEFAULT 0,
  `PaymentType` INT DEFAULT 0,
  `PredecessorBookingId` INT DEFAULT NULL,
  `PromoAmount` DECIMAL(12,4) DEFAULT NULL,
  `PromoCode` VARCHAR(255) DEFAULT NULL,
  `PromoCodeId` INT DEFAULT NULL,
  `ReachOutTime` INT DEFAULT NULL,
  `Status` INT DEFAULT 0,
  `Street` VARCHAR(255) DEFAULT NULL,
  `SuccessorBookingId` INT DEFAULT NULL,
  `SystemPhase` INT DEFAULT NULL,
  `TransactionDate` DATETIME DEFAULT NULL,
  `TransactionId` VARCHAR(255) DEFAULT NULL,
  `TravelFee` DECIMAL(12,4) DEFAULT NULL,
  `UserNotifiedPreBooking` INT DEFAULT 0,
  `UserNotifiedPreBookingEmail` INT DEFAULT 0,
  `Zip` VARCHAR(255) DEFAULT NULL,
  `AGPromoCodeId` INT DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `PaymentIntent` VARCHAR(255) DEFAULT NULL,
  `Product` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`BookingId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingExtra` (
  `BookingExtraId` INT NOT NULL AUTO_INCREMENT,
  `AdminNotes` TEXT,
  `BookingId` INT DEFAULT NULL,
  `UnfillNotification` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingExtraId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProduct` (
  `BookingProductId` INT NOT NULL AUTO_INCREMENT,
  `Amount` DECIMAL(12,4) DEFAULT NULL,
  `BookingId` INT DEFAULT NULL,
  `CategoryId` INT DEFAULT NULL,
  `CheckInTime` DATETIME DEFAULT NULL,
  `CheckOutTime` DATETIME DEFAULT NULL,
  `Discount` DECIMAL(12,4) DEFAULT NULL,
  `DiscountedAmount` DECIMAL(12,4) DEFAULT NULL,
  `DispatchId` VARCHAR(255) DEFAULT NULL,
  `DispatchType` INT DEFAULT 0,
  `Duration` INT DEFAULT NULL,
  `EventId` VARCHAR(255) DEFAULT NULL,
  `GuestId` INT DEFAULT NULL,
  `PreparationTime` INT DEFAULT NULL,
  `Product` VARCHAR(255) DEFAULT NULL,
  `ProductId` INT DEFAULT NULL,
  `RealFinishTime` DATETIME DEFAULT NULL,
  `RealStartTime` DATETIME DEFAULT NULL,
  `SameTime` INT DEFAULT 0,
  `StaffAmount` DECIMAL(12,4) DEFAULT NULL,
  `StaffEarning` DECIMAL(12,4) DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `StaffNotes` TEXT,
  `StaffVacConflict` INT DEFAULT 0,
  `StartTime` DATETIME DEFAULT NULL,
  `Status` INT DEFAULT 0,
  `Therapist` VARCHAR(255) DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `ForceStaffAllot` INT DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `AcceptedOn` DATETIME DEFAULT NULL,
  `DiffAccepted` INT DEFAULT NULL,
  PRIMARY KEY (`BookingProductId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProductAddOn` (
  `BookingProductAddOnId` INT NOT NULL AUTO_INCREMENT,
  `AddOn` VARCHAR(255) DEFAULT NULL,
  `AddOnId` INT DEFAULT NULL,
  `Amount` DECIMAL(12,4) DEFAULT NULL,
  `BookingAddOnPaymentId` INT DEFAULT NULL,
  `BookingId` INT DEFAULT NULL,
  `BookingProductId` INT DEFAULT NULL,
  `Duration` INT DEFAULT NULL,
  `ExtraAddOn` VARCHAR(255) DEFAULT NULL,
  `ExtraNotified` INT DEFAULT 0,
  `RequestStatus` INT DEFAULT NULL,
  `StaffAmount` DECIMAL(12,4) DEFAULT NULL,
  `StaffEarning` DECIMAL(12,4) DEFAULT NULL,
  `AutoAccepted` INT DEFAULT 0,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `Status` INT DEFAULT 0,
  PRIMARY KEY (`BookingProductAddOnId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProductExtra` (
  `BookingProductExtraId` INT NOT NULL AUTO_INCREMENT,
  `BookingProductId` INT DEFAULT NULL,
  `ExtraValue` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `ExtraTitle` VARCHAR(255) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingProductExtraId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProductDispatch` (
  `BookingProductDispatchId` INT NOT NULL AUTO_INCREMENT,
  `DispatchId` VARCHAR(255) DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `Status` INT DEFAULT 0,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingProductDispatchId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingAddOnPayment` (
  `BookingAddOnPaymentId` INT NOT NULL AUTO_INCREMENT,
  `Amount` DECIMAL(12,4) DEFAULT NULL,
  `BookingId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `PaymentIntent` VARCHAR(255) DEFAULT NULL,
  `PaymentStatus` INT DEFAULT 0,
  `TransactionDate` DATETIME DEFAULT NULL,
  `TransactionId` VARCHAR(255) DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  PRIMARY KEY (`BookingAddOnPaymentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingPreference` (
  `BookingPreferenceId` INT NOT NULL AUTO_INCREMENT,
  `GlobalDispatchDefault` INT DEFAULT NULL,
  `InstantConfirmation` INT DEFAULT NULL,
  `IsFilterApplied` INT DEFAULT 0,
  `IsPriorityActive` INT DEFAULT 0,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingPreferenceId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `DispatchFilter` (
  `DispatchFilterId` INT NOT NULL AUTO_INCREMENT,
  `IsActive` INT DEFAULT 0,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`DispatchFilterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingTip` (
  `BookingTipId` INT NOT NULL AUTO_INCREMENT,
  `BookingId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `PaymentStatus` INT DEFAULT 0,
  `TipAmount` DECIMAL(12,4) DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `TransactionDate` DATETIME DEFAULT NULL,
  `TransactionId` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`BookingTipId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Category` (
  `CategoryId` INT NOT NULL AUTO_INCREMENT,
  `ColorCode` VARCHAR(255) DEFAULT NULL,
  `CurOrder` INT DEFAULT NULL,
  `Description` TEXT,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Deleted` INT DEFAULT 0,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`CategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Center` (
  `CenterId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Address` VARCHAR(255) DEFAULT NULL,
  `Latitude` DECIMAL(12,4) DEFAULT NULL,
  `Longitude` DECIMAL(12,4) DEFAULT NULL,
  `ServiceArea` INT DEFAULT NULL,
  `Contact` VARCHAR(255) DEFAULT NULL,
  `SosContact` VARCHAR(255) DEFAULT NULL,
  `CheckInProximity` INT DEFAULT NULL,
  `TodayLeadTime` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`CenterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SpecialRequest` (
  `SpecialRequestId` INT NOT NULL AUTO_INCREMENT,
  `SpecialRequestName` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `IsUSerDefined` INT DEFAULT 0,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`SpecialRequestId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Faq` (
  `FaqId` INT NOT NULL AUTO_INCREMENT,
  `Answer` TEXT,
  `CurOrder` INT DEFAULT NULL,
  `Question` TEXT,
  `Type` INT DEFAULT 0,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`FaqId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FaqSection` (
  `FaqSectionId` INT NOT NULL AUTO_INCREMENT,
  `FaqId` INT DEFAULT NULL,
  `SectionId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`FaqSectionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Guest` (
  `GuestId` INT NOT NULL AUTO_INCREMENT,
  `BookingId` INT DEFAULT NULL,
  `Contact` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `Gender` INT DEFAULT 0,
  `LastUpdated` DATETIME DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Notes` TEXT,
  `Relation` VARCHAR(255) DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  PRIMARY KEY (`GuestId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GuestUser` (
  `GuestUserId` INT NOT NULL AUTO_INCREMENT,
  `DeviceId` VARCHAR(255) DEFAULT NULL,
  `Platform` VARCHAR(255) DEFAULT NULL,
  `FcmToken` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`GuestUserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Language` (
  `LanguageId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Code` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`LanguageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `LocationRequest` (
  `LocationRequestId` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME DEFAULT NULL,
  `Distance` DECIMAL(12,4) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `Latitude` DECIMAL(12,4) DEFAULT NULL,
  `Longitude` DECIMAL(12,4) DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `UserEmail` VARCHAR(255) DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  `UserName` VARCHAR(255) DEFAULT NULL,
  `UserPhone` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`LocationRequestId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Message` (
  `MessageId` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME DEFAULT NULL,
  `Type` INT DEFAULT 0,
  `Title` VARCHAR(255) DEFAULT NULL,
  `Description` TEXT,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`MessageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Product` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `CategoryId` INT DEFAULT NULL,
  `CurOrder` INT DEFAULT NULL,
  `Deleted` INT DEFAULT 0,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `OrganisationLocationId` INT DEFAULT NULL,
  `PreparationTime` INT DEFAULT NULL,
  `ProductExtraMaxSelect` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ProductId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ProductDuration` (
  `ProductDurationId` INT NOT NULL AUTO_INCREMENT,
  `Amount` DECIMAL(12,4) DEFAULT NULL,
  `Duration` INT DEFAULT NULL,
  `ProductId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ProductDurationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ProductExtra` (
  `ProductExtraId` INT NOT NULL AUTO_INCREMENT,
  `ExtraTitle` VARCHAR(255) DEFAULT NULL,
  `ExtraValue` VARCHAR(255) DEFAULT NULL,
  `ProductId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ProductExtraId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ProductTranslation` (
  `ProductTranslationId` INT NOT NULL AUTO_INCREMENT,
  `Description` TEXT,
  `LanguageId` INT DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `ProductId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ProductTranslationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PromoCode` (
  `PromoCodeId` INT NOT NULL AUTO_INCREMENT,
  `Class` INT DEFAULT 0,
  `Code` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `CurrentCount` INT DEFAULT NULL,
  `EndDate` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `MaxAmount` DECIMAL(12,4) DEFAULT NULL,
  `MinPurchaseAmount` DECIMAL(12,4) DEFAULT NULL,
  `Mode` INT DEFAULT 0,
  `RedeemCount` INT DEFAULT NULL,
  `StartDate` DATETIME DEFAULT NULL,
  `Type` INT DEFAULT 0,
  `Value` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`PromoCodeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PromoCodeCategory` (
  `PromoCodeCategoryId` INT NOT NULL AUTO_INCREMENT,
  `CategoryId` INT DEFAULT NULL,
  `PromoCodeId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`PromoCodeCategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Rating` (
  `RatingId` INT NOT NULL AUTO_INCREMENT,
  `BookingId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `EaseOfBooking` VARCHAR(255) DEFAULT NULL,
  `Experience` VARCHAR(255) DEFAULT NULL,
  `Feedback` TEXT,
  `Professionalism` VARCHAR(255) DEFAULT NULL,
  `Quality` VARCHAR(255) DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  `Value` VARCHAR(255) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`RatingId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Section` (
  `SectionId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Type` INT DEFAULT 0,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`SectionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Staff` (
  `StaffId` INT NOT NULL AUTO_INCREMENT,
  `Address` VARCHAR(255) DEFAULT NULL,
  `AppleIdentifier` VARCHAR(255) DEFAULT NULL,
  `AverageRating` DECIMAL(12,4) DEFAULT NULL,
  `COCONRating` DECIMAL(12,4) DEFAULT NULL,
  `City` VARCHAR(255) DEFAULT NULL,
  `CompanyName` VARCHAR(255) DEFAULT NULL,
  `Contact` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `Deleted` INT DEFAULT 0,
  `DeviceId` VARCHAR(255) DEFAULT NULL,
  `FacebookId` VARCHAR(255) DEFAULT NULL,
  `FcmToken` VARCHAR(255) DEFAULT NULL,
  `Gender` INT DEFAULT 0,
  `GoogleEmail` VARCHAR(255) DEFAULT NULL,
  `GoogleId` VARCHAR(255) DEFAULT NULL,
  `IbanNumber` VARCHAR(255) DEFAULT NULL,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `KvkNumber` VARCHAR(255) DEFAULT NULL,
  `LastMessageRead` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Sequence` INT DEFAULT NULL,
  `StaffGroupId` INT DEFAULT NULL,
  `StaffType` INT DEFAULT 0,
  `Status` INT DEFAULT 0,
  `TipReceived` DECIMAL(12,4) DEFAULT NULL,
  `TotalRatings` DECIMAL(12,4) DEFAULT NULL,
  `Zip` VARCHAR(255) DEFAULT NULL,
  `BookingId` INT DEFAULT NULL,
  `CurrentBookingId` INT DEFAULT NULL,
  `Platform` VARCHAR(255) DEFAULT NULL,
  `RefreshToken` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`StaffId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffBlockTime` (
  `StaffBlocKTimeId` INT NOT NULL AUTO_INCREMENT,
  `BlocKTimeId` INT DEFAULT NULL,
  `EndTime` DATETIME DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `StartTime` DATETIME DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`StaffBlocKTimeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffCategory` (
  `StaffCategoryId` INT NOT NULL AUTO_INCREMENT,
  `CategoryId` INT DEFAULT NULL,
  `Rate` DECIMAL(12,4) DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`StaffCategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffMessage` (
  `StaffMessageId` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME DEFAULT NULL,
  `Date` DATETIME DEFAULT NULL,
  `Description` TEXT,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `Tag` INT DEFAULT 0,
  `Title` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`StaffMessageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffVacation` (
  `StaffVacationId` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME DEFAULT NULL,
  `DayCount` INT DEFAULT NULL,
  `EndTime` DATETIME DEFAULT NULL,
  `EventId` VARCHAR(255) DEFAULT NULL,
  `Notes` TEXT,
  `RequestId` INT DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `StartTime` DATETIME DEFAULT NULL,
  `Status` INT DEFAULT 0,
  `Template` INT DEFAULT 0,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`StaffVacationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffSchedule` (
  `StaffScheduleId` INT NOT NULL AUTO_INCREMENT,
  `LastUpdated` DATETIME DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `FridayBlockTimeId` INT DEFAULT NULL,
  `FridayEndDate` DATETIME DEFAULT NULL,
  `FridayEndTime` DATETIME DEFAULT NULL,
  `FridayStartDate` DATETIME DEFAULT NULL,
  `FridayStartTime` DATETIME DEFAULT NULL,
  `MondayBlockTimeId` INT DEFAULT NULL,
  `MondayEndDate` DATETIME DEFAULT NULL,
  `MondayEndTime` DATETIME DEFAULT NULL,
  `MondayStartDate` DATETIME DEFAULT NULL,
  `MondayStartTime` DATETIME DEFAULT NULL,
  `SaturdayBlockTimeId` INT DEFAULT NULL,
  `SaturdayEndDate` DATETIME DEFAULT NULL,
  `SaturdayEndTime` DATETIME DEFAULT NULL,
  `SaturdayStartDate` DATETIME DEFAULT NULL,
  `SaturdayStartTime` DATETIME DEFAULT NULL,
  `ScheduleType` INT DEFAULT 0,
  `SundayBlockTimeId` INT DEFAULT NULL,
  `SundayEndDate` DATETIME DEFAULT NULL,
  `SundayEndTime` DATETIME DEFAULT NULL,
  `SundayStartDate` DATETIME DEFAULT NULL,
  `SundayStartTime` DATETIME DEFAULT NULL,
  `ThursdayBlockTimeId` INT DEFAULT NULL,
  `ThursdayEndDate` DATETIME DEFAULT NULL,
  `ThursdayEndTime` DATETIME DEFAULT NULL,
  `ThursdayStartDate` DATETIME DEFAULT NULL,
  `ThursdayStartTime` DATETIME DEFAULT NULL,
  `TuesdayBlockTimeId` INT DEFAULT NULL,
  `TuesdayEndDate` DATETIME DEFAULT NULL,
  `TuesdayEndTime` DATETIME DEFAULT NULL,
  `TuesdayStartDate` DATETIME DEFAULT NULL,
  `TuesdayStartTime` DATETIME DEFAULT NULL,
  `WednesdayBlockTimeId` INT DEFAULT NULL,
  `WednesdayEndDate` DATETIME DEFAULT NULL,
  `WednesdayEndTime` DATETIME DEFAULT NULL,
  `WednesdayStartDate` DATETIME DEFAULT NULL,
  `WednesdayStartTime` DATETIME DEFAULT NULL,
  PRIMARY KEY (`StaffScheduleId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffRegistration` (
  `StaffRegistrationId` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME DEFAULT NULL,
  `Email` VARCHAR(255) DEFAULT NULL,
  `IsRegCodeUsed` INT DEFAULT 0,
  `LastUpdated` DATETIME DEFAULT NULL,
  `Phone` VARCHAR(255) DEFAULT NULL,
  `RegistrationCode` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`StaffRegistrationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffGroup` (
  `StaffGroupId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL,
  `IsUsedInFilter` INT DEFAULT 0,
  `Priority` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`StaffGroupId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffProduct` (
  `StaffProductId` INT NOT NULL AUTO_INCREMENT,
  `ProductId` INT DEFAULT NULL,
  `Rate` DECIMAL(12,4) DEFAULT NULL,
  `StaffCategoryId` INT DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`StaffProductId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffMetadata` (
  `StaffMetadataId` INT NOT NULL AUTO_INCREMENT,
  `AutoAcceptAddonRequest` INT DEFAULT 0,
  `IsAddEditScheduleEnable` INT DEFAULT 0,
  `Rank` INT DEFAULT NULL,
  `ShowOutsideOffers` INT DEFAULT 0,
  `StaffId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `RegisteredFrom` INT DEFAULT NULL,
  `StaffRegistrationId` INT DEFAULT NULL,
  PRIMARY KEY (`StaffMetadataId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SosContact` (
  `SosContactId` INT NOT NULL AUTO_INCREMENT,
  `Contact` VARCHAR(255) DEFAULT NULL,
  `Deleted` INT DEFAULT 0,
  `Type` INT DEFAULT 0,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`SosContactId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Archive` INT DEFAULT 0,
  `CSNotes` TEXT,
  `City` VARCHAR(255) DEFAULT NULL,
  `ClientSource` INT DEFAULT NULL,
  `CoconNotes` TEXT,
  `Contact` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `CustomerId` VARCHAR(255) DEFAULT NULL,
  `DOB` DATETIME DEFAULT NULL,
  `Distance` DECIMAL(12,4) DEFAULT NULL,
  `Elevator` INT DEFAULT 0,
  `Email` VARCHAR(255) DEFAULT NULL,
  `FcmToken` VARCHAR(255) DEFAULT NULL,
  `Floor` VARCHAR(255) DEFAULT NULL,
  `FromCMS` INT DEFAULT 0,
  `Gender` INT DEFAULT 0,
  `HouseNumber` VARCHAR(255) DEFAULT NULL,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Notes` TEXT,
  `PreferredLanguage` INT DEFAULT NULL,
  `ReachOutTime` INT DEFAULT NULL,
  `Street` VARCHAR(255) DEFAULT NULL,
  `Therapist` VARCHAR(255) DEFAULT NULL,
  `TherapistNotes` TEXT,
  `Zip` VARCHAR(255) DEFAULT NULL,
  `FullAddress` VARCHAR(255) DEFAULT NULL,
  `AppleId` VARCHAR(255) DEFAULT NULL,
  `FacebookId` VARCHAR(255) DEFAULT NULL,
  `GoogleId` VARCHAR(255) DEFAULT NULL,
  `Latitude` DECIMAL(12,4) DEFAULT NULL,
  `Longitude` DECIMAL(12,4) DEFAULT NULL,
  `IsCalPermitted` INT DEFAULT 0,
  `DeviceId` VARCHAR(255) DEFAULT NULL,
  `Platform` VARCHAR(255) DEFAULT NULL,
  `RefreshToken` VARCHAR(255) DEFAULT NULL,
  `LastMessageRead` DATETIME DEFAULT NULL,
  `CoconLastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`UserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `UserMessage` (
  `UserMessageId` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME DEFAULT NULL,
  `Date` DATETIME DEFAULT NULL,
  `Description` TEXT,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  `Title` VARCHAR(255) DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  PRIMARY KEY (`UserMessageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AccountDeleteFeedback` (
  `AccountDeleteFeedbackId` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  `IssueType` INT DEFAULT 0,
  `Feedback` TEXT,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`AccountDeleteFeedbackId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingSpecialRequest` (
  `BookingSpecialRequestId` INT NOT NULL AUTO_INCREMENT,
  `BookingId` INT DEFAULT NULL,
  `SpecialRequestId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingSpecialRequestId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingChannel` (
  `BookingChannelId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingChannelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingInvoiceData` (
  `BookingInvoiceDataId` INT NOT NULL AUTO_INCREMENT,
  `BookingId` INT DEFAULT NULL,
  `InvoiceEmail` VARCHAR(255) DEFAULT NULL,
  `InvoiceStripeStatus` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `InvoiceId` VARCHAR(255) DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingInvoiceDataId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Organisation` (
  `OrganisationId` INT NOT NULL AUTO_INCREMENT,
  `Type` INT DEFAULT 0,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Email` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`OrganisationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `OrganisationLocation` (
  `OrganisationLocationId` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(255) DEFAULT NULL,
  `Contact` VARCHAR(255) DEFAULT NULL,
  `ContactNumber` VARCHAR(255) DEFAULT NULL,
  `Deleted` INT DEFAULT 0,
  `Distance` DECIMAL(12,4) DEFAULT NULL,
  `Elevator` INT DEFAULT 0,
  `Email` VARCHAR(255) DEFAULT NULL,
  `EncryptedOrganisationLocationId` VARCHAR(255) DEFAULT NULL,
  `Floor` VARCHAR(255) DEFAULT NULL,
  `HouseNumber` VARCHAR(255) DEFAULT NULL,
  `ImagePath` VARCHAR(255) DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `OrganisationId` INT DEFAULT NULL,
  `ReachOutTime` INT DEFAULT NULL,
  `Street` VARCHAR(255) DEFAULT NULL,
  `Zip` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`OrganisationLocationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BusinessType` (
  `BusinessTypeId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BusinessTypeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffOrganisation` (
  `StaffOrganisationId` INT NOT NULL AUTO_INCREMENT,
  `OrganisationLocationId` INT DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`StaffOrganisationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingInstructions` (
  `BookingInstructionsId` INT NOT NULL AUTO_INCREMENT,
  `Type` INT DEFAULT 0,
  `Title` VARCHAR(255) DEFAULT NULL,
  `Body` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingInstructionsId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ActionsLog` (
  `ActionsLogId` INT NOT NULL AUTO_INCREMENT,
  `AdminId` INT DEFAULT NULL,
  `TableName` VARCHAR(255) DEFAULT NULL,
  `TableId` INT DEFAULT NULL,
  `ActionType` INT DEFAULT 0,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ActionsLogId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `StaffAccountDeleteFeedback` (
  `StaffAccountDeleteFeedbackId` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME DEFAULT NULL,
  `Feedback` TEXT,
  `IssueType` INT DEFAULT 0,
  `LastUpdated` DATETIME DEFAULT NULL,
  `StaffId` INT DEFAULT NULL,
  PRIMARY KEY (`StaffAccountDeleteFeedbackId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ServiceZipCode` (
  `ServiceZipCodeId` INT NOT NULL AUTO_INCREMENT,
  `Zipcode` VARCHAR(255) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ServiceZipCodeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CategoryHourlyRate` (
  `CategoryHourlyRateId` INT NOT NULL AUTO_INCREMENT,
  `CategoryId` INT DEFAULT NULL,
  `EndTime` VARCHAR(32) DEFAULT NULL,
  `FridayRate` DECIMAL(12,4) DEFAULT NULL,
  `MondayRate` DECIMAL(12,4) DEFAULT NULL,
  `SaturdayRate` DECIMAL(12,4) DEFAULT NULL,
  `StartTime` VARCHAR(32) DEFAULT NULL,
  `SundayRate` DECIMAL(12,4) DEFAULT NULL,
  `ThursdayRate` DECIMAL(12,4) DEFAULT NULL,
  `TuesdayRate` DECIMAL(12,4) DEFAULT NULL,
  `WednesdayRate` DECIMAL(12,4) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`CategoryHourlyRateId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BookingProductAppliedRate` (
  `BookingProductAppliedRateId` INT NOT NULL AUTO_INCREMENT,
  `BookingProductId` INT DEFAULT NULL,
  `Rate` DECIMAL(12,4) DEFAULT NULL,
  `Created` DATETIME DEFAULT NULL,
  `LastUpdated` DATETIME DEFAULT NULL,
  PRIMARY KEY (`BookingProductAppliedRateId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=1;