const MESSAGE = {
    REQ_DATA_ERROR: "Please enter the required information.",
    SWW_TRY_AGAIN: "Sorry, it seems something went wrong, please try again.",
    TOKEN_NOT_UPDATED: "Token not updated.",
    INVALID_EMAIL: "Please enter a valid email address.",
    USER_NOT_FOUND_TRY_AGAIN: "Sorry, user not found, please try again.",
    INVALID_USER_CREDENTIALS: "User credentials are invalid.",
    INVALID_FILE_TYPE: "Invalid file type.",
    IMAGE_NOT_UPLOADED: "Image not uploaded.",
    USER_ALREADY_EXIST: "User already exist.",
    INVALID_AUTH_TOKEN: "Invalid auth token.",
    FAILED_TO_SIGN_UP: "Failed to sign up.",
    USER_NOT_UPDATED_TRY_AGAIN: "User not updated, please try again!",
    USER_EMAIL_ALREADY_EXIST: "User with this email address already exists, to select this user, you need to go back and select from the existing users' list.",
    INVALID_HEADERS: "Invalid headers.",
    TOKEN_FETCH_SUCCESS: "Token fetch successfully.",
    USER_FETCH_SUCCESS: "Users fetch successfully.",
    USER_LOGGED_IN: "Logged in successfully.",
    PAYMENT_METHOD_FETCH_SUCCESS: "Payment Methods fetch successfully.",
    IMAGE_UPLOADED: "Image uploaded successfully.",
    SIGN_UP_SUCCESS: "Sign up successfull.",
    PROFILE_UPDATED_SUCCESS: "Profile updated successfully.",
    USER_EXTRA_UPDATES_SUCCESS: "Users extras updated successfully.",
    USER_CAN_BE_REGISTERED: "User can be registered.",
    USER_DETAIL_FETCH_SUCCESS: "User detail fetched successfully.",
    LOGGED_OUT_SUCCESS: "Logged out successfully.",
    USER_PROFILE_UPDATED_SUCCESS: "User profile updated successfully.",
    CREATE_ADDON_FAILED: "Failed to create add-on.",
    ADDON_CAT_ADD_FAILED: "Failed to add category(s) in add-on.",
    ADDON_CAT_REM_FAILED: "Failed to remove category(s) from add-on.",
    ADDON_SAVE_SUCCESS: "Add-on added successfully.",
    UPDATE_ADDON_SUCCESS: "Add-on updated successfully.",
    UPDATE_ADDON_FAILED: "Failed to update add-on.",
    DEL_ADDON_FAILED: "Failed to delete add-on(s).",
    DEL_ADDON_SUCCESS: "Add-on deleted successfully.",
    BOOK_ANALYTICS_SUCCESS: "Booking analytics fetch successfully.",
    USER_ANALYTICS_SUCCESS: "User analytics fetched successfully.",
    PROD_ANALYTICS_SUCCESS: "Product analytics fetched successfully.",
    TOKEN_NOT_PROVIDED: "Token not provided.",
    USER_LOGGED_OUT: "User logged out.",
    PROCEED: "Proceed",
    SUCCESS: "Success",
    CATEGORY_FETCH_SUCCESS: "Category fetch successfully.",
    CREATE_CATEGORY_FAILED: "Failed to create category.",
    CATEGORY_SAVE_SUCCESS: "Category added successfully.",
    UPDATE_CATEGORY_FAILED: "Failed to update category.",
    UPDATE_CATEGORY_SUCCESS: "Category Updated successfully",
    REORDERING_SUCCESS: "Reordering successful.",
    FAQ_FETCH_SUCCESS: "FAQ fetch successfully.",
    FAQ_SAVE_SUCCESS: "FAQ added successfully.",
    UPDATE_FAQ_FAILED: "Failed to update FAQ.",
    UPDATE_FAQ_SECTION_FAILED: "Failed to update FAQ section.",
    UPDATE_FAQ_SUCCESS: "FAQ updated successfully.",
    DEL_FAQ_SUCCESS: "FAQ(s) deleted successfully.",
    MESSAGES_FETCH_SUCCESS: "Messages fetch successfully.",
    MESSAGE_SENT_SUCCESS: "Message sent successfully.",
    MESSAGE_NOT_AVAILABLE: "Sorry, it seems message is not available in system. please try again.",
    MESSAGE_UPDATE_FAILED: "Message not updated, please try again!",
    MESSAGE_UPDATE_SUCCESS: "Message updated successfully.",
    MESSAGE_DEL_SUCCESS: "Message(s) deleted successfully.",
    METADATA_FETCH_SUCCESS: "Metadata fetch successfully.",
    LOC_REQ_FETCH_SUCCESS: "Location Requests fetched successfully.",
    PRODUCT_CREATE_FAILED: "Failed to create product.",
    PRODUCT_CREATE_SWW: "Sorry, it seems something went wrong while creating product. Please try again.",
    PRODUCT_SAVE_SUCCESS: "Product added successfully.",
    PRODUCT_FETCH_SUCCESS: "Product fetch successfully.",
    PRODUCT_NOT_AVAILABLE: "Sorry, it seems product is not available in system. please try again.",
    PRODUCT_UPDATE_FAILED: "Failed to update product.",
    PRODUCT_UPDATE_SWW: "Sorry, it seems something went wrong while updating product. Please try again.",
    PRODUCT_UPDATE_SUCCESS: "Product updated successfully.",
    PRODUCT_DELETE_FAILED: "Failed to delete product.",
    PRODUCT_DELETE_SUCCESS: "Product deleted successfully.",
    PROMOCODE_FETCH_SUCCESS: "Promo codes fetch successfully.",
    PROMOCODE_ALREADY_EXIST: "Sorry, promo code already exists.",
    PROMOCODE_CREATE_SWW: "Sorry, it seems something went wrong while creating promo code. Please try again.",
    PROMOCODE_SAVE_SUCCESS: "Promo code added successfully.",
    PROMOCODE_NOT_AVAILABLE: "Sorry, it seems promo code is not available in system. Please try again.",
    PROMOCODE_UPDATE_FAILED: "Failed to update promo code.",
    PROMOCODE_UPDATE_SWW: "Sorry, it seems something went wrong while updating promo code. Please try again.",
    PROMOCODE_UPDATE_SUCCESS: "Promo code updated successfully.",
    PROMO_NOT_APPLICABLE_IOS_1: "Promo code not applicable for app 1.0",
    PROMOCODE_DEL_FAILED: "Promo code deleted successfully.",
    REPORT_BOOKING_NOT_EXIST: "No bookings exist for selected configuration.",
    USER_NOT_EXIST: "User does not exist.",
    BOOKING_FETCH_SUCCESS: "Bookings fetch successfully.",
    BOOKING_NOT_AVAILABLE: "Sorry, it seems booking is not available in system. Please try again.",
    RATINGS_SAVE_FAILED: "Failed to save ratings.",
    RATINGS_SAVE_SUCCESS: "Ratings saved successfully.",
    RATINGS_FETCH_SUCCESS: "Ratings fetch successfully.",
    SOMETHING_WENT_WRONG: "Sorry, it seems something went wrong, please try again.",
    BOOKING_DETAIL_FETCH_SUCCESS: "Booking Details fetch successfully.",
    INVALID_PRODUCT_CONFIG: "Sorry, it seems product configuration is not valid.",
    INVALID_ADDON_CONFIG: "Sorry, it seems add-on configuration is not valid.",
    INVALID_BOOKING_AMOUNT: "Sorry, it seems booking final amount is not valid.",
    INVALID_BOOK_PAID_AMOUNT: "Sorry, it seems booking paid amount is not valid.",
    STAFF_NOT_AVAILABLE_F_BOOK: "Staff no more available for booking.",
    BOOKING_SAVE_FAILED: "Booking not saved.",
    BOOKING_SAVE_SUCCESS: "Booking saved successfully.",
    TIP_ALREADY_GIVEN: "Tip already given.",
    TIP_SAVE_FAILED: "Tip not saved.",
    TIP_FETCH_SUCCESS: "Tip data fetched successfully.",
    TIP_SAVE_SUCCESS: "Booking Tip saved.",
    BOOKING_UPDATE_SUCCESS: "Booking updated successfully.",
    ADDON_NOT_FOUND: "AddOn not found.",
    BOOKING_PRODUCT_NOT_EXIST: "Booking product not exists.",
    STAFF_AVAIL_CHECKED: "Staff Availability.",
    BOOKING_STATUS_UPDATE_SUCCESS: "Booking Status updated successfully.",
    BOOKING_PAY_FIRST: "Please do booking payment first.",
    BOOKING_CANCELLED: "Booking cancelled.",
    BOOKING_EXTRAS_UPDATE_SUCCESS: "Booking extras updated successfully.",
    TIME_SLOT_FETCH_SUCCESS: "Time-slots fetch successfully.",
    PAST_BOOKING_NOT_ALLOWED: "Sorry, booking date can't be from past.",
    STAFF_FETCH_SUCCESS: "Staff fetch successfully.",
    INVALID_CATEGORY: "Please select valid Category.",
    STAFF_EMAIL_ALREADY_EXIST: "Staff member with provided email address already exists, please change and try again.",
    STAFF_SAVE_FAILED: "Failed to create staff.",
    STAFF_CREATE_SWW: "Sorry, it seems something went wrong while creating staff. Please try again.",
    STAFF_SAVE_SUCCESS: "Staff added successfully.",
    STAFF_UPDATE_FAILED: "Failed to update staff.",
    STAFF_UPDATE_SUCCESS: "Staff updated successfully.",
    STAFF_DELETE_SUCCESS: "Staff deleted successfully.",
    STAFF_NOT_AVAILABLE: "Staff not available.",
    STAFF_BOOKING_FETCH_SUCCESS: "Staff bookings fetched successfully.",
    INVALID_DATETIME: "Invalid Date/Time",
    BOOKING_PRODUCT_ID_REQ: "BookingProductId not provided.",
    NOTES_REQUIRED: "Notes not provided.",
    THERAPIST_EVENT_SAVED_SUCCESS: "Event status updated successfully.",
    DEVICE_ID_REQUIRED: "Please provide device id.",
    STAFF_LOGIN_SUCCESS: "Staff logged in successfully.",
    STAFF_DETAIL_FETCH_SUCCESS: "Staff detail fetched successfully.",
    STAFF_NOT_FOUND: "Sorry, staff not found. Please try again.",
    BOOKING_CONFLICT_MESSAGE: "It seems vacation dates you have entered are having one or more booking(s) already scheduled. Would you still like to go ahead and allow vacation?",
    VACATION_REQ_SUCCESS: "Vacation request submitted successfully.",
    VACATION_FETCH_SUCCESS: "Vacations fetched successfully.",
    VAC_REQ_NOT_EXIST: "Request does not exist",
    VACATION_RETREAT_SUCCESS: "Vacation request retreated successfully.",
    SOS_SENT_SUCCESS: "SOS message sent successfully.",
    TWILIO_TOK_FETCH_SUCCESS: "Twilio token fetch successfully.",
    INVALID_DATE: "Invalid date.",
    STAFF_SCH_UPDATE_SUCCESS: "Staff schedule updated successfully.",
    STAFF_SCH_FETCH_SUCCESS: "Staff schedule fetch successfully.",
    TOS_FETCH_SUCCESS: "TOS fetch successfully.",
    BOOK_NOT_EXIST_REFRESH: "Sorry, It seems the booking does not exist anymore, please refresh list.",
    OBJECT_FETCH_SUCCESS: "Object fetch successfully.",
    BADGE_CHECK_SUCCESS: "Booking badge count checked successfully.",
    CATEGORY_NOT_AVAILABLE: "Sorry, it seems category is not available in system. Please try again.",
    CRON_SUCCESS: "Cron job ran successfully.",
    REGISTRATION_CODE_USED: "Sorry, It seems your registration code is already used, please request for a new one from admin.",
    REGISTRATION_CODE_NOT_FOUND: "Sorry, entered registration code is not valid.",
    REGISTRATION_CODE_VALID: "Registration code verified successfully, code is valid.",
    REGISTRATION_CODE_SENT: "Registration code sent to your entered Email or Phone.",
    STAFF_METADATA_SAVE_FAILED: "Failed to create staff metadata record.",
    ENDDATE_BEFORE_START: "End date cannot be less than start date.",
    SWITCH_DEFAULT_UNHANDLED: "Switch default has no definition.",
    REQUEST_ACCEPTED: "Request Accepted.",
    GROUP_ALREADY_EXIST: "Group already exist.",
    DISPATCH_SETTING_UPDATED: "Dispatch settings updated successfully.",
    STAFF_ALREADY_ASSIGNED: "Staff already assigned.",
    REGISTRATION_CODE_EXPIRED: "Registration code expired.",
    PRODUCT_ALREADY_ACCEPTED: "Product already accepted.",
    INVALID_TOTAL_AMOUNT: "Invalid total amount.",
    CANNOT_ACCEPT_PAST_BOOKING: "Cannot accept booking from past time.",
    SERVER_STATUS_FETCH_SUCCESS: "Server status fetch successfully.",
    REQUES_NOT_ALLOWED: "Request not allowed.",
    IMAGE_NOT_DELETED: "Sorry, the image was not deleted",
    USER_DELETED_SUCCESS: "User was deleted successfully.",
    FEEDBACK_SAVED_SUCCESS: "Feedback was saved successfully.",
    USER_ACCOUNT_DELETED: "User has deleted the account.",
    SPECIAL_REQUEST_UPDATE_SWW: "Sorry, it seems something went wrong while saving data. Please try again.",
    INVOICE_NOT_CREATED: "Sorry, it seems something went wrong while creating the invoice, but the booking has been created.",
    REQ_DATA_USER_ERROR: "Please enter the required information for user.",
    BOOKING_DRAFT_SUCCESS: "Draft saved successfully.",
    INVOICE_NOT_SENT: "Sorry, it seems something went wrong while sending the invoice, but the booking has been created.",
    INVALID_BOOKING: "Invalid Booking Details.",
    ORGANISATION_EMAIL_ALREADY_EXIST: "Organisation with provided email address already exists, please change and try again.",
    CREATE_ORGANISATION_FAILED: "Failed to create organisation.",
    CREATE_ORGANISATION_FAILED: "Failed to update organisation.",
    CREATE_ORGANISATION_LOCATION_FAILED: "Failed to create organisation location.",
    UPDATE_ORGANISATION_LOCATION_FAILED: "Failed to update organisation location.",
    UPDATE_ORGANISATION_ADMIN_FAILED: "Failed to update admin data.",
    ORGANISATION_SAVE_SUCCESS: "Organisation saved successfully.",
    PASSWORD_CREATION_FAILED: "Password could not be generated.",
    ADMIN_ACCOUNT_NOT_CREATED: "Admin account could not be created.",
    ORGANISATION_FETCH_SUCCESS: "Organisations fetched successfully.",
    ORGANISATION_DELETE_SUCCESS: "Organisation deleted successfully.",
    REACHOUTTIME_FAILED: "Reachout time could not be calculated.",
    INVALID_ORGANISATION: "Sorry, it seems organisation details are invalid.",
    ORGANISATION_UPDATE_SUCCESS: "Organisation updated successfully.",
    ORGANISATION_PASSWORD_UPDATE_SUCCESS: "Password updated successfully. Please check email.",
    UPDATE_ORGANISATION_ADMIN_FAILED: "Failed to update organisation's admin data.",
    STAFF_ORGANISATION_SAVE_FAILED: "Failed to create staff organisation record.",
    BOOKING_INSTRUCTION_FETCH_SUCCESS: "Data fetched successfully.",
    ADMIN_EMAIL_ALREADY_EXIST: "Admin with provided email address already exists, please change and try again.",
    ADMIN_SAVE_SUCCESS: "Admin created successfully.",
    ADMIN_UPDATE_SUCCESS: "Admin updated successfully.",
    ADMIN_DELETE_SUCCESS: "Admin deleted successfully.",
    INVALID_ADMIN: "Admin does not exist.",
    ZIP_INVALID: "Zipcode is not valid.",
    NOTES_SUCCESS: "Notes saved successfully.",
    
};

const PUSH = {
    /**
     * Includes only static strings.
     * There are some push where title is also dynamically generated.
     */
    TITLE: {
        ADDON_REQ_RECEIVED: "Add-on request received",
        BOOKING_UPDATED_F_CMS: "Booking updated",
        STAFF_CHECK_IN: "Therapist checked in",
        STAFF_CHECK_OUT: "Therapist checked out",
        BOOKING_CANCELLED_F_CMS: "Booking cancelled",
        NEW_BOOKING_F_CMS: "New booking created",
        AG_PROMO_RECEIVED: "New promo code received",
        CHAT_MSG_BY_COCON: "Message from COCON",
        UPCOMING_BOOKING: "Upcoming Booking",
        PROFILE_UPDATED: "Profile updated"
    },

    DESCRIPTION: {
        PROFILE_UPDATED: "Your profile is updated by COCON."
    },

    SCREEN: {
        MESSAGES: "Messages",
        BOOKINGS: "Bookings",
        BOOKING_DETAIL: "Booking Detail",
        CHAT_SUPPORT: "ChatSupport",
        PROFILE_UPDATE: "ProfileUpdate",
        INCOMING_REQUEST: "IncomingRequest",
        MY_BOOKINGS: "MyBookings",
        SKILLS: "Skills"
    }
}
const OTHERS={
    AUTO_BLOCK:"Automatic block time"
}

const DATE_TIME_FORMAT = {
    /**
     * Codes used in constants.
     * D: Day
     * M: Month
     * Y: Year
     * T: Time
     * Z: Zone
     * H: Hour (24 hr format: 01-24)
     * m: Minute
     * s: Second
     * C: Comma (",")
     * c: Colon (":")
     * L: Forward slash ("/")
     * _: Single space (" ")
     * da: Dash ("-")
     */
    z: "z",
    Z: "Z",
    HHcmm: "HH:mm",
    HHcmmcss: "HH:mm:ss",
    MMLYYYY: "MM/YYYY",
    MMLDDLYYYY: "MM/DD/YYYY",
    DDLMMLYYYY: "DD/MM/YYYY",
    YYYYdaMMdaDD: "YYYY-MM-DD",
    DD_MMM_YYYY: "DD MMM YYYY",
    MMM_DDC_YYYY: "MMM DD, YYYY",
    MMLDDLYYYY_Z: "MM/DD/YYYY Z",
    YYYYMMDDTHHMMSS: "YYYYMMDDTHHMMSS",
    MMLDDLYYYY_HHcmm: "MM/DD/YYYY HH:mm",
    MMM_DD_YYYY_HHcmm: "MMM DD YYYY HH:mm",
    DD_MMM_YYYYC_HHcmm: "DD MMM YYYY, HH:mm",
    DD_MMM_YYYYC_HHcmm_Z: "DD MMM YYYY, HH:mm Z",
    DD_MMM_YYYYC_HHcmm_z: "DD MMM YYYY, HH:mm z",
    MMM_DD_YYYYC_HHcmm: "MMM DD YYYY, HH:mm",
    MMLDDLYYYY_HHcmm_Z: "MM/DD/YYYY HH:mm Z",
    MMLDDLYYYY_HHcmmcss_Z: "MM/DD/YYYY HH:mm:ss Z",
    YYYYdaMMdaDD_HHcmmcss_Z: "YYYY-MM-DD HH:mm:ss Z",
    ISO_FORMAT: "YYYY-MM-DDTHH:mm:ss.sss"
}

const DELETE_REASON={
    SERVICE_ANYMORE: "I don't use this service anymore.",
    HOW_IT_WORKS:"I don't understand how it works.",
    TECHNICAL_ISSUE:"I have technical issues with the app.",
    FINDING_HARD:"Finding hard to use the app.",
    ISSUE_WITH_SERVICE:"Issues with services provided.",
    OTHER:"Other"
}

module.exports = {
    MESSAGE,
    PUSH,
    DATE_TIME_FORMAT,
    DELETE_REASON,
    OTHERS
}