module.exports = {
    ADDONS: "AddOn",
    ADDON_CATEGORY: "AddOnCategory",
    ADMIN: "Admin",
    ADMIN_NOTIFICATION_CONTACT: "AdminNotificationContact",
    APP_VERSIONS: "AppVersion",
    BANK: "Bank",
    BOOKINGS: "Booking",
    BOOKING_EXTRA: "BookingExtra",
    BOOKING_PRODUCTS: "BookingProduct",
    BOOKING_PRODUCT_ADDONS: "BookingProductAddOn",
    BOOKING_PRODUCT_EXTRA: "BookingProductExtra",
    BOOKING_PRODUCT_DISPATCH: "BookingProductDispatch",
    BOOKING_ADDON_PAYMENTS: "BookingAddOnPayment",
    BOOKING_PREFERENCE: "BookingPreference",
    DISPATCH_FILTERS: "DispatchFilter",
    BOOKING_TIPS: "BookingTip",
    CATEGORIES: "Category",
    CENTER: "Center",
    SPECIAL_REQUEST: "SpecialRequest",
    FAQ: "Faq",
    FAQ_SECTION: "FaqSection",
    GUESTS: "Guest",
    GUEST_USERS: "GuestUser",
    LANGUAGE: "Language",
    LOCATION_REQUEST: "LocationRequest",
    MESSAGES: "Message",
    PRODUCTS: "Product",
    PRODUCT_DURATIONS: "ProductDuration",
    PRODUCT_EXTRA: "ProductExtra",
    PRODUCT_TRANSLATIONS: "ProductTranslation",
    PROMOCODES: "PromoCode",
    PROMOCODE_CATEGORIES: "PromoCodeCategory",
    RATINGS: "Rating",
    SECTION: "Section",
    STAFF: "Staff",
    STAFF_BLOCK_TIME: "StaffBlockTime",
    STAFF_CATEGORY: "StaffCategory",
    STAFF_MESSAGES: "StaffMessage",
    STAFF_VACATIONS: "StaffVacation",
    STAFF_SCHEDULE: "StaffSchedule",
    STAFF_REGISTRATION : "StaffRegistration",
    STAFF_GROUP: "StaffGroup",
    STAFF_PRODUCT: "StaffProduct",
    STAFF_METADATA: "StaffMetadata",
    SOS_CONTACT: "SosContact",
    USERS: "User",  
    USER_MESSAGES: "UserMessage",
    ACCOUNT_DELETE_FEEDBACK: "AccountDeleteFeedback",
    BOOKING_SPECIAL_REQUEST: "BookingSpecialRequest",
    BOOKING_CHANNEL:"BookingChannel",
    BOOKING_INVOICE_DATA:"BookingInvoiceData",
    ORGANISATION:"Organisation",
    ORGANISATION_LOCATION:"OrganisationLocation",
    BUSINESS_TYPE:"BusinessType",
    STAFF_ORGANISATION:"StaffOrganisation",
    BOOKING_INSTRUCTIONS:"BookingInstructions",
    ACTION_LOG:"ActionsLog",
    STAFF_ACCOUNT_DELETE_FEEDBACK: "StaffAccountDeleteFeedback",
    SERVICE_ZIPCODE: "ServiceZipCode",
    CATEGORY_HOURLY_RATE: "CategoryHourlyRate",
    BOOKING_PRODUCT_APPLIED_RATE: "BookingProductAppliedRate",
}